#!/usr/bin/env node
'use strict';

/**
 * Build the browser bundle of the shared data engine.
 *
 * Wraps each lib/*.js (CommonJS) into an SB.define() factory so the same engine
 * code runs in the browser via the VFS/require shim (webapp/src/vfs.js).
 *
 * Output: webapp/src/engine-lib.js
 */

const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const LIB = path.join(ROOT, 'lib');
const OUT = path.join(ROOT, 'webapp', 'src', 'engine-lib.js');

// Modules to include (skip zip.js/images.js/store.js — browser has its own).
const MODULES = ['config', 'po', 'reader', 'generator', 'validate'];

let out = `// AUTO-GENERATED by tools/story-builder/build-webapp.js — do not edit.\n`;
out += `// Wraps the shared lib/*.js engine for the browser via SB.define().\n\n`;
out += `(function(){ 'use strict';\n`;
out += `if (!window.SB || !window.SB.define) { throw new Error('vfs.js must load first'); }\n`;
out += `const D = window.SB.define;\n\n`;

for (const name of MODULES) {
  const file = path.join(LIB, `${name}.js`);
  if (!fs.existsSync(file)) { console.warn('skip missing', name); continue; }
  let code = fs.readFileSync(file, 'utf8');
  // Provide a fake __dirname for config.js (it also reads SB_ROOT override).
  out += `D('/lib/${name}', function(require, module, exports){\n`;
  out += `const __dirname = '/lib';\n`;
  out += code;
  out += `\n});\n\n`;
}

out += `})();\n`;

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, out, 'utf8');
console.log('Wrote', path.relative(ROOT, OUT), `(${MODULES.join(', ')})`);
